theme: jekyll-theme-minimal
title: "DNSC 6330 in One Sentence"
description: Responsible Machine Learning examines machine learning as a sociotechnical system embedded within institutional, regulatory, and market environments.
baseurl: /dnsc-6330-responsible-ML
url: https://makinwumi.github.io